<a href="https://colab.research.google.com/github/pauloalexx/Python_study/blob/main/Biblioteca_Aula4_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **AULA 4 - Selecionar valores do dataset**

---

> Selecionando valores específicos do *DataFrame*... 

```
operadores de indexação ([] .)

filter()

loc[]

iloc[]

máscaras booleanas (== > < >= <=)

```

> **SITUAÇÃO PROBLEMA**

Vamos supor que você seja dono de um banco em Taiwan que oferta serviço de crédito. Você tem em mãos uma tabela em excel com dados dos clientes que contrataram o serviço de crédito. 

`Objetivo`: apresentar um panorama consolidado sobre a situação dos clientes no banco para o restante da empresa.

**PASSO 2: FILTRAR INFORMAÇÕES ESPECÍFICAS PARA ENTENDER OS PADRÕES:**

![DATA_ANALYSIS.drawio (4).png]()

In [ ]:
# Importando a biblioteca

import pandas as pd

In [ ]:
# Lendo dados tabulares

credit = pd.read_excel("/content/clientes_credito.xlsx")

Para selecionar os valores de uma determinada coluna, podemos utilizar o operador `[]` (operador de indexação) como mostrado abaixo:

In [ ]:
# Acessando UMA coluna

credit['valor_credito']

0         20000
1        120000
2         90000
3         50000
4         50000
          ...
29995    220000
29996    150000
29997     30000
29998     80000
29999     50000
Name: valor_credito, Length: 30000, dtype: int64

A mesma operação pode ser feita com o uso do operador` .` como mostrado abaixo:

In [ ]:
credit.valor_credito

0         20000
1        120000
2         90000
3         50000
4         50000
          ...
29995    220000
29996    150000
29997     30000
29998     80000
29999     50000
Name: valor_credito, Length: 30000, dtype: int64

Múltiplas colunas podem ser selecionadas. Podemos usar uma lista para especificar os rótulos das colunas desejada na seleção:

In [ ]:
# Acessando MÚLTIPLAS colunas

credit[['valor_pag_abr_2005','valor_pag_mai_2005','valor_pag_jun_2005','valor_pag_jul_2005','valor_pag_ago_2005','valor_pag_set_2005']]

,valor_pag_abr_2005,valor_pag_mai_2005,valor_pag_jun_2005,valor_pag_jul_2005,valor_pag_ago_2005,valor_pag_set_2005
0,0,0,0,0,689,0
1,2000,0,1000,1000,1000,0
2,5000,1000,1000,1000,1500,1518
3,1000,1069,1100,1200,2019,2000
4,679,689,9000,10000,36681,2000
...,...,...,...,...,...,...
29995,1000,5000,3047,5003,20000,8500
29996,0,0,129,8998,3526,1837
29997,3100,2000,4200,22000,0,0
29998,1804,52964,1926,1178,3409,85900
29999,1000,1000,1000,1430,1800,2078

Podemos usar o método `filter` para selecionar colunas baseada em seus nomes ou rótulos:

In [ ]:
# Filtrando colunas

credit.filter(like='set')

       status_pag_set_2005  extrato_set_2005  valor_pag_set_2005
0                        2              3913                   0
1                       -1              2682                   0
2                        0             29239                1518
3                        0             46990                2000
4                       -1              8617                2000
...                    ...               ...                 ...
29995                    0            188948                8500
29996                   -1              1683                1837
29997                    4              3565                   0
29998                    1             -1645               85900
29999                    0             47929                2078

[30000 rows x 3 columns]

Podemos utilizar as propriedades `iloc` e `loc` para acessar grupos de linhas e colunas:

In [ ]:
# Acessando UMA linha

credit.loc[0]

Unnamed: 0                 0
ID                         1
valor_credito          20000
sexo                       2
nivel_escolaridade         2
estado_civil               1
idade                     24
status_pag_set_2005        2
status_pag_ago_2005        2
status_pag_jul_2005       -1
status_pag_jun_2005       -1
status_pag_mai_2005       -2
status_pag_abr_2005       -2
extrato_set_2005        3913
extrato_ago_2005        3102
extrato_jul_2005         689
extrato_jun_2005           0
extrato_mai_2005           0
extrato_abr_2005           0
valor_pag_set_2005         0
valor_pag_ago_2005       689
valor_pag_jul_2005         0
valor_pag_jun_2005         0
valor_pag_mai_2005         0
valor_pag_abr_2005         0
Name: 0, dtype: int64

In [ ]:
# Acessando MÚLTIPLAS linhas

credit.loc[0:2]

,Unnamed: 0,ID,valor_credito,sexo,nivel_escolaridade,estado_civil,idade,status_pag_set_2005,status_pag_ago_2005,status_pag_jul_2005,...,extrato_jul_2005,extrato_jun_2005,extrato_mai_2005,extrato_abr_2005,valor_pag_set_2005,valor_pag_ago_2005,valor_pag_jul_2005,valor_pag_jun_2005,valor_pag_mai_2005,valor_pag_abr_2005
0,0,1,20000,2,2,1,24,2,2,-1,...,689,0,0,0,0,689,0,0,0,0
1,1,2,120000,2,2,2,26,-1,2,0,...,2682,3272,3455,3261,0,1000,1000,1000,0,2000
2,2,3,90000,2,2,2,34,0,0,0,...,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000

In [ ]:
# Acessando linhas E colunas

credit.loc[ 0:30,  [ 'ID', 'valor_credito', 'sexo', 'nivel_escolaridade' ] ]

    ID  valor_credito  sexo  nivel_escolaridade
0    1          20000     2                   2
1    2         120000     2                   2
2    3          90000     2                   2
3    4          50000     2                   2
4    5          50000     1                   2
5    6          50000     1                   1
6    7         500000     1                   1
7    8         100000     2                   2
8    9         140000     2                   3
9   10          20000     1                   3
10  11         200000     2                   3
11  12         260000     2                   1
12  13         630000     2                   2
13  14          70000     1                   2
14  15         250000     1                   1
15  16          50000     2                   3
16  17          20000     1                   1
17  18         320000     1                   1
18  19         360000     2                   1
19  20         180000     2                   1
20  21         130000     2                   3
21  22         120000     2                   2
22  23          70000     2                   2
23  24         450000     2                   1
24  25          90000     1                   1
25  26          50000     1                   3
26  27          60000     1                   1
27  28          50000     2                   3
28  29          50000     2                   3
29  30          50000     1                   1
30  31         230000     2                   1

In [ ]:
credit.iloc[ 0:4,  0:4 ]

   Unnamed: 0  ID  valor_credito  sexo
0           0   1          20000     2
1           1   2         120000     2
2           2   3          90000     2
3           3   4          50000     2

A propriedade `loc` utiliza os índices ou rótulos dos eixos das linhas e colunas como forma de endereçamento dos elementos. Já o operador `iloc` utiliza números inteiros correspondentes à posição dos eixos (linhas e colunas).

Podemos também selecionar valores das linhas utilizando operadores lógicos:

In [ ]:
# Acessar linhas a partir de máscaras booleanas

credit[credit["nivel_escolaridade"] == 2]

,Unnamed: 0,ID,valor_credito,sexo,nivel_escolaridade,estado_civil,idade,status_pag_set_2005,status_pag_ago_2005,status_pag_jul_2005,...,extrato_jul_2005,extrato_jun_2005,extrato_mai_2005,extrato_abr_2005,valor_pag_set_2005,valor_pag_ago_2005,valor_pag_jul_2005,valor_pag_jun_2005,valor_pag_mai_2005,valor_pag_abr_2005
0,0,1,20000,2,2,1,24,2,2,-1,...,689,0,0,0,0,689,0,0,0,0
1,1,2,120000,2,2,2,26,-1,2,0,...,2682,3272,3455,3261,0,1000,1000,1000,0,2000
2,2,3,90000,2,2,2,34,0,0,0,...,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000
3,3,4,50000,2,2,1,37,0,0,0,...,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000
4,4,5,50000,1,2,1,57,-1,0,-1,...,35835,20940,19146,19131,2000,36681,10000,9000,689,679
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29990,29990,29991,140000,1,2,1,41,0,0,0,...,139110,138262,49675,46121,6000,7000,4228,1505,2000,2000
29991,29991,29992,210000,1,2,1,34,3,2,2,...,2500,2500,2500,2500,0,0,0,0,0,0
29994,29994,29995,80000,1,2,2,34,2,2,2,...,79384,77519,82607,81158,7000,3500,0,7000,0,4000
29997,29997,29998,30000,1,2,2,37,4,3,2,...,2758,20878,20582,19357,0,0,22000,4200,2000,3100
29999,29999,30000,50000,1,2,1,46,0,0,0,...,49764,36535,32428,15313,2078,1800,1430,1000,1000,1000

A condição dentro dos colchetes de seleção `credit["nivel_escolaridade"] == 2` verifica para quais linhas a coluna `nivel_escolaridade` tem um valor igual a 2, ou seja, clientes que apresentam nível de escolaridade equivalente à graduação.